plugins:
  duplication:
    enabled: false
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    enabled: false
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 200
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 200
  nested-control-flow:
    config:
      threshold: 6
  return-statements:
    config:
      threshold: 8
  similar-code:
    enabled: false
## exclude UI folder in the Analysis of made by code climate
exclude_patterns:
- "__tests__/**/*.js"
- "__mocks__/**/*.js"
